# Generated by Django 6.0 on 2025-12-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_catergory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catergory',
        ),
    ]
