# Generated by Django 6.0 on 2025-12-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_sub_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
