# Generated by Django 6.0 on 2025-12-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_alter_category_category_name'),
        ('vendor', '0018_remove_product_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
