# Generated by Django 6.0 on 2025-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
