# Generated by Django 6.0 on 2025-12-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_alter_user_user_photo_seller'),
        ('User', '0010_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='Guest.seller'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='Guest.user'),
        ),
    ]
