# Generated by Django 6.0 on 2025-12-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Replied', 'Replied'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
