# Generated by Django 6.0 on 2025-12-17 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/')),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_guests', to='administrator.place')),
            ],
        ),
    ]
