# Generated by Django 6.0 on 2025-12-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
