# Generated by Django 6.0 on 2025-12-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_remove_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='user_contact',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='user_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='user_photo',
        ),
    ]
