# Generated by Django 6.0 on 2025-12-18 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_rename_address_user_user_address_and_more'),
        ('administrator', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user/user_photo/'),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_email', models.CharField(max_length=100)),
                ('seller_password', models.CharField(max_length=100)),
                ('seller_contact', models.CharField(max_length=100)),
                ('seller_address', models.CharField(max_length=100)),
                ('seller_photo', models.ImageField(blank=True, null=True, upload_to='seller/seller_photo/')),
                ('seller_proof', models.ImageField(blank=True, null=True, upload_to='seller/seller_proof/')),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_guests', to='administrator.place')),
            ],
        ),
    ]
